
export const Roller = [
    {name: "cw", fullName: "Company Worker", typicalFeatures: "Conservative, dutiful, predictable", positiveQualities: "Organising ability, practical common sense, hard-working, self-disciplined", allowableWeaknesses: "Lack of flexibility, Unresponsiveness to unproven ideas", letters: ["g","a","h","d","b","f","e"], points: [], total: 0},
    {name: "cp", fullName: "Chairperson", typicalFeatures: "Calm, Self confident, controlled", positiveQualities: "A capacity for treating and welcoming all potential contributions on their merits, strong sense of objectivity", allowableWeaknesses: "No more than ordinary in terms of intellect or creative ability", letters: ["d","b","a","h","f","c","g"], points: [], total: 0},
    {name: "sh", fullName: "Shaper", typicalFeatures: "Highly strung, outgoing, dynamic", positiveQualities: "Drive and a readiness to challenge inertia, ineffectiveness, complacency or self-deception", allowableWeaknesses: "Proneness to provocation, irritability and impatience", letters: "fecbdga", points: [], total: 0},
    {name: "pl", fullName: "Plant", typicalFeatures: "Individualistic. Serious minded, unorthodox", positiveQualities: "Genius, imagination, intellect, knowledge", allowableWeaknesses: "Up in the clouds, inclined to disregard practical details or protocol", letters: "cgdehaf", points: [], total: 0},
    {name: "ri", fullName: "Resource Investigator", typicalFeatures: "Extroverted, enthusiastic, curious, communicative", positiveQualities: "A capacity for contacting people, exploring anything new, an ability to respond to challenge", allowableWeaknesses: "Liable to lose interest once initial fascination has passed", letters: "acfgehd", points: [], total: 0},
    {name: "me", fullName: "Monitor Evaluator", typicalFeatures: "Sober, unemotional, prudent", positiveQualities: "Judgement, discretion, hard headedness", allowableWeaknesses: "Lacks inspiration or the ability to motivate others", letters: "hdgcaeb", points: [], total: 0},
    {name: "tw", fullName: "Team Worker", typicalFeatures: "Socially oriented, rather mild, sensitive", positiveQualities: "An ability to respond to people and to situations, and to promote team spirit", allowableWeaknesses: "Indecisiveness at moments of crisis", letters: "bfeacbh", points: [], total: 0},
    {name: "cf", fullName: "Complete Finisher", typicalFeatures: "Painstaking, orderly, conscientious, anxious", positiveQualities: "A capacity for follow-through", allowableWeaknesses: "A tendency to worry about small 'things', A reluctance to 'let go'", letters: "ehbfgdc", points: [], total: 0},
]